### ISSUE TITLE
Wont let me re-activate 

### ISSUE THREAD

**Issue by dreamwonderx** [PLhery/unfollowNinja#71]
I temporarily deleted my account. I re-stored my account about a few weeks ago. Once I tried to gain access to this service it kept giving me the same message, it’s saying I need to log out & log back in. I do that, then it repeats the message. Not sure what else I need to do.

**Comment by plhery** [comment]
Oh, I guess the message was not clear, I should rewrite it.

I bet you got "It seems that your Twitter account has been deactivated: Log in again to reactivate the service."

This is because there are two login buttons / (for two Twitter apps) and you need to click on the second one to continue

**Comment by dreamwonderx** [comment]
> Oh, I guess the message was not clear, I should rewrite it.
> 
> I bet you got "It seems that your Twitter account has been deactivated: Log in again to reactivate the service."
> 
> This is because there are two login buttons / (for two Twitter apps) and you need to click on the second one to continue

I do log out, as I mentioned I follow the steps. I do not get prompt to another screen. I log out as it says and log back in just for it to repeat the same message. Not sure what else I am doing wrong here?

**Comment by plhery** [comment]
You are supposed to click on "enable DM notifications", not "log out"
(the message is not clear I agree)

**Comment by dreamwonderx** [comment]
Thank you very much for the help I’m sorry if I sounded like an idiot. This made it more clear!

**Comment by dreamwonderx** [comment]
> You are supposed to click on "enable DM notifications", not "log out"
> (the message is not clear I agree)

Thank you for the help I appreciate it all is fixed, that was very more clear!!
